#!/bin/bash -e

if [ -z "$1" ]; then
  echo "Usage:"
  echo "  deploy my.bucket.name"
  echo "The bucket will be used to store the Lambda code when deploying."
  echo "It will be created if needed"
  exit 1
else
  s3Bucket=$1
fi

output_template_file=$(mktemp)

# build Lambda code for Linux
docker build -t "cloudformation-lambda-cookies" .
docker run "cloudformation-lambda-cookies" > dist/lambda.zip

(
  cd resize
  docker build -t "cloudformation-lambda-resize" .
  docker run "cloudformation-lambda-resize" > ../dist/lambda-resize.zip
)

(
  cd site-builder
  docker build -t "cloudformation-lambda-site-builder" .
  docker run "cloudformation-lambda-site-builder" > ../dist/lambda-site-builder.zip
)

# create the target S3 bucket if needed
aws s3 ls ${s3Bucket} > /dev/null
if [ $? -ne 0 ]; then
  aws s3 mb ${s3Bucket}
fi

# create and upload the CloudFormation package
aws cloudformation package \
    --template-file app.yml \
    --output-template-file ${output_template_file} \
    --s3-bucket ${s3Bucket}

# deploy it
aws cloudformation deploy \
    --template-file ${output_template_file} \
    --stack-name ProtectedPictures \
    --capabilities CAPABILITY_IAM \
    --parameter-overrides file://dist/config.json
