#!/bin/bash -e

if [ -z "$1" ]; then
  echo "Usage:"
  echo "  generate_random_albums <number of albums>"
  echo "Removes all bucket contents, downloads 6 pictures for each album from unsplash.com, giving each album a random name, uploads them to the original bucket."
  exit 1
else
  webBucket="$(sed -n 's/  "webBucket=\(.*\)"\,/\1/p' dist/config.json)"
  sourceBucket="$(sed -n 's/  "sourceBucket=\(.*\)"\,/\1/p' dist/config.json)"
  resizedBucket="$(sed -n 's/  "resizedBucket=\(.*\)"\,/\1/p' dist/config.json)"
  numberOfAlbums=$1
fi

echo "Removing all files in web, source & resized buckets"
for bucket in "$webBucket" "$sourceBucket" "$resizedBucket"; do
  aws s3 rm --recursive "s3://$bucket" >> /dev/null 2>&1 || true
done

prevMD5=()
for (( albumIndex = 0; albumIndex < numberOfAlbums; albumIndex++ )); do
  albumNumber=$RANDOM
  let "albumNumber %= 1000"
  for (( picIndex = 0; picIndex < 6; picIndex++ )); do
    echo "Downloading pic $picIndex for album $albumIndex"
    pic="$(mktemp).jpg"
    curl -sL https://source.unsplash.com/random -o "$pic"
    while [[ " ${prevMD5[@]} " =~ " $(md5sum "$pic" | awk '{print $1}') " ]]; do
      curl -sL https://source.unsplash.com/random -o "$pic"
    done
    prevMD5+=("$(md5sum "$pic" | awk '{print $1}')")
    aws s3 cp "$pic" "s3://$sourceBucket/pics/original/Album $albumNumber/0$picIndex.jpg" >> /dev/null 2>&1
  done
done
