#!/bin/bash -e

if [ -z "$2" ]; then
  echo "Usage:"
  echo "  generate_random_albums <web bucket> <original bucket> <resized bucket> <number of albums>"
  echo "Removes all bucket contents, downloads 6 pictures for each album from unsplash.com, giving each album a random name, uploads them to the original bucket."
  exit 1
else
  webBucket=$1
  originalBucket=$2
  resizedBucket=$3
  numberOfAlbums=$4
fi

echo "Removing all files in web, original & resized buckets"
for bucket in "$webBucket" "$originalBucket" "$resizedBucket"; do
  aws s3 rm --recursive "s3://$bucket" >> /dev/null 2>&1
done

prevMD5=()
for (( albumIndex = 0; albumIndex < numberOfAlbums; albumIndex++ )); do
  albumNumber=$RANDOM
  let "albumNumber %= 1000"
  for (( picIndex = 0; picIndex < 6; picIndex++ )); do
    echo "Downloading pic $picIndex for album $albumIndex"
    pic="$(mktemp).jpg"
    curl -sL https://source.unsplash.com/random -o "$pic"
    while [[ " ${prevMD5[@]} " =~ " $(md5sum "$pic" | awk '{print $1}') " ]]; do
      curl -sL https://source.unsplash.com/random -o "$pic"
    done
    prevMD5+=("$(md5sum "$pic" | awk '{print $1}')")
    aws s3 cp "$pic" "s3://$originalBucket/pics/original/Album $albumNumber/0$picIndex.jpg" >> /dev/null 2>&1
  done
done
